version: '3.5'
services:
  sonarqube:
    image: ${IMAGE}
    container_name: ${APP_NAME}
    volumes:
      # - ./conf:/opt/sonarqube/conf
      - ./data:/opt/sonarqube/data
      - ./logs:/opt/sonarqube/logs
      - ./extensions:/opt/sonarqube/extensions
    environment:
    - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/${APP_NAME}
    - SONARQUBE_JDBC_USERNAME=${DB_USER}
    - SONARQUBE_JDBC_PASSWORD=${DB_PASSWORD}
    ports:
     - "${WEB_PORT}:9000"
    links:
      - sonarqube-db:db
    depends_on:
      - sonarqube-db
  sonarqube-db:
    container_name: ${APP_NAME}-db
    image: postgres:alpine
    environment:
      POSTGRES_DB: ${APP_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    # ports:
    # - ${DB_PORT}:5432
    tty: true
    restart: on-failure