version: '3'
services:
  web:
    image: sonarqube
    container_name: ${APP_NAME}
    volumes:
      - ./conf:/opt/sonarqube/conf
      - ./data:/opt/sonarqube/data
      - ./logs:/opt/sonarqube/logs
    environment:
    - SONARQUBE_JDBC_URL=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_SCHEMA}
    - SONARQUBE_JDBC_USERNAME=${DB_USER}
    - SONARQUBE_JDBC_PASSWORD=${DB_PASSWORD}
    ports:
     - "${WEB_PORT}:9000"
    links:
      - db:db
    depends_on:
      - db
  db:
    container_name: ${APP_NAME}-db
    image: postgres:alpine
    environment:
      POSTGRES_DB: ${DB_SCHEMA}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
    - 5432:5432
    tty: true
    restart: on-failure