version: '3'
services:
  web:
    image: ${IMAGE}
    container_name: ${APP_NAME}
    volumes:
      - ./conf:/opt/sonarqube/conf
      - ./data:/opt/sonarqube/data
      - ./logs:/opt/sonarqube/logs
      - ./extensions:/opt/sonarqube/extensions
    environment:
    - SONARQUBE_JDBC_URL=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${APP_NAME}
    - SONARQUBE_JDBC_USERNAME=${APP_NAME}
    - SONARQUBE_JDBC_PASSWORD=${APP_NAME}
    ports:
     - "${WEB_PORT}:9000"
    links:
      - db:db
    depends_on:
      - db
  db:
    container_name: ${APP_NAME}-db
    image: postgres:alpine
    environment:
      POSTGRES_DB: ${APP_NAME}
      POSTGRES_USER: ${APP_NAME}
      POSTGRES_PASSWORD: ${APP_NAME}
    ports:
    - ${DB_PORT}:5432
    tty: true
    restart: on-failure