version: '3'
services:
  web:
    image: sonarqube
    container_name: ${APP_NAME}
    volumes:
      - .:/var/www/html/
      - ./.docker/apache.conf:/etc/apache2/sites-enabled/000-default.conf
    environment:
    - SONARQUBE_JDBC_URL=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_SCHEMA}
    - SONARQUBE_JDBC_USERNAME=${DB_USER}
    - SONARQUBE_JDBC_PASSWORD=${DB_PASSWORD}
    ports:
     - "${WEB_PORT}:9000"
    networks:
      - dev.engesoftware.com.br
networks:
  dev.engesoftware.com.br:
    external:
      name: dev.engesoftware.com.br