version: '3'
services:
  web:
    image: sonarqube
    container_name: ${APP_NAME}
    volumes:
      - ./conf:/opt/sonarqube/conf
      - ./data:/opt/sonarqube/data
      - ./logs:/opt/sonarqube/logs
      - ./extensions:/opt/sonarqube/extensions
    environment:
    - SONARQUBE_JDBC_URL=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_SCHEMA}
    - SONARQUBE_JDBC_USERNAME=${DB_USER}
    - SONARQUBE_JDBC_PASSWORD=${DB_PASSWORD}
    ports:
     - "${WEB_PORT}:9000"